apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-depl
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: amdevops36/enhancedcicd:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key:  MYSQL_DB_HOST
            - name: MYSQL_DB_DNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key:  MYSQL_DB_DNAME
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key:  MYSQL_DB_USERNAME
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key:  MYSQL_DB_PASSWORD

---

apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: springboot-srv    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: springboot-srv
spec:
  type: NodePort              # The service will be exposed by opening a Port on each node and proxying it.
  selector:
    app: springboot   # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
    - name: http
      port: 8080
      targetPort: 8080