---
- hosts: all
  vars:
    mysql_db_host: "localhost"
    mysql_db_port: "3306"
    mysql_db_dname: "DB"
    mysql_db_user: "root"
    mysql_db_password: "root"

  tasks:
    - name: Copier le fichier WAR
      copy:
        src: /home/vagrant/Product-0.0.1-SNAPSHOT.jar
        dest: /home/devops/Product-0.0.1-SNAPSHOT.jar

    - name: Copier le Dockerfile
      copy:
        src: /home/vagrant/Dockerfile
        dest: /home/devops/Dockerfile

    - name: Copier le fichier docker-compose.yml
      copy:
        src: /home/vagrant/docker-compose.yml
        dest: /home/devops/docker-compose.yml

    - name: Déployer la stack Docker Compose
      shell: |
        export MYSQL_DB_HOST={{ mysql_db_host }}
        export MYSQL_DB_PORT={{ mysql_db_port }}
        export MYSQL_DB_DNAME={{ mysql_db_dname }}
        export MYSQL_DB_USER={{ mysql_db_user }}
        export MYSQL_DB_PASSWORD={{ mysql_db_password }}
        docker compose -f /home/devops/docker-compose.yml up
      args:
        chdir: /home/devops
      environment:
        MYSQL_DB_HOST: "{{ mysql_db_host }}"
        MYSQL_DB_PORT: "{{ mysql_db_port }}"
        MYSQL_DB_DNAME: "{{ mysql_db_dname }}"
        MYSQL_DB_USER: "{{ mysql_db_user }}"
        MYSQL_DB_PASSWORD: "{{ mysql_db_password }}"



